# Generated by Django 2.1.4 on 2018-12-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strings', models.CharField(max_length=20)),
                ('serched_date', models.DateTimeField()),
                ('user', models.ManyToManyField(to='user.user_singup_model')),
            ],
        ),
    ]
